        logger.exception("Main bot exited due to an error:")
